spring:
  jpa:
    show-sql: true
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/spring_base?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password

springdoc:
  swagger-ui:
    path: /api-docs
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
  paths-to-match:
    - /api/**

jwt:
  secret: 4626379cadc10451644ebfc33bdef68993cd3edc426640f8c28758cd853dbfa5a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z
  accessToken:
    expiration: 7200000  # 2 hours in milliseconds
  refreshToken:
    expiration: 864000000  # 10 days in milliseconds